version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: creativesolution0315
      POSTGRES_USER: postgres
      POSTGRES_DB: CreativeSolution
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
